# Generated by Django 3.2.9 on 2024-01-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_alter_board_members_alter_board_workspace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boarduser',
            name='board',
        ),
        migrations.RemoveField(
            model_name='boarduser',
            name='member',
        ),
        migrations.RemoveField(
            model_name='group',
            name='board',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='members',
        ),
        migrations.RemoveField(
            model_name='workspaceuser',
            name='member',
        ),
        migrations.RemoveField(
            model_name='workspaceuser',
            name='workspace',
        ),
        migrations.RemoveField(
            model_name='task',
            name='group',
        ),
        migrations.RemoveField(
            model_name='task',
            name='users',
        ),
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True),
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='BoardUser',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Workspace',
        ),
        migrations.DeleteModel(
            name='WorkspaceUser',
        ),
    ]
