# Generated by Django 3.2.9 on 2024-01-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_auto_20240111_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='expire_at',
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('d', 'Done'), ('w', 'Working on it'), ('u', 'Unfinished')], default='w', max_length=1),
        ),
    ]
